### ISSUE TITLE
Izveidot Google Forms jautājumus

### ISSUE THREAD

**Issue by edzya** [edzya/RTU_project#1]
- Google Forms jautājumi;
- Izdomāt/pierakstīt jautājumus;

**Comment by edzya** [comment]
Procesā

**Comment by edzya** [comment]
https://forms.gle/1fZq2abQAp9fbLUaA

**Comment by edzya** [comment]
Comments are welcome

**Comment by svinacienitajs** [comment]
@edzya  
- Trešais jautājums,  vārdu veiksmi varētu pārmainīt uz "Izredzi" vai kautko formālu tml. Serviss varētu būt uz vārdu Pakalpojums.

Jautājumu ziņa varētu pajautāt:
"Vai ir kautkas īpašs ,ko jūs varētu izdarīt savādāk nekā pārējie konkurenti?" tāda domā par to kā izvēlētās grupas pakalpojums atšķirās no pārējiem.
