### ISSUE TITLE
Uzrakstīt 3. nodaļu - PPS

### ISSUE THREAD

**Issue by edzya** [edzya/RTU_project#11]
PPS - ieteicams izdalīt funkcionālās un nefunkcionālās. 
(Ieteikums rakstīt tabulā vai strukturētā tekstā ar prasību numerāciju) Izveidot un pievienot 2 lietotāju saskarnes UI/UX prototipus .

//Lietotāja saskarnes prototipiem būs savs issue.

**Comment by svinacienitajs** [comment]
- https://www.figma.com/community/file/1292408626745092119 

@edzya Es te figmā uzmetu ideju kā tas varētu strādāt, jo... bļin pat nezinu kā īsti varētu iztestēt šo programmu/ sistēmu jo viņa balstās uz 1.cilvēks ievada datus un 2. cilvēks iegust datus. Takā, es varētu pameiģināt uztaisīt  programmu kas ļauj vienam useram ievadīt kautko, sakartot raksturīgi figmas failam, un arī pievienot kautkadu kalendāra loģiku
