### ISSUE TITLE
Izveidot dokumentu par projektu

### ISSUE THREAD

**Issue by edzya** [edzya/RTU_project#2]
Dokuments, noformēts pēc RTU formatēšanas noteikumiem

**Comment by edzya** [comment]
@svinacienitajs, man ir ideja. Varbūt vari izveidot dokumentu RTU nodrošinātajā Sharepointā, un noshare'ot linku, lai abi vienlaicīgi varam strādāt katrs pie savas nodaļas.

**Comment by svinacienitajs** [comment]
@edzya - https://rtucloud1.sharepoint.com/:w:/s/RTUScheduleservice/EeWYYy-hSQJHnUndwkv-4_0B5GEPUcwslDmVqMVkyiR1eQ?e=6DhDwj ,šitā?

**Comment by edzya** [comment]
@svinacienitajs Atjaunotā versija, tur kaut kas ar stiliem bija nepareizi. Varbūt vari ielikt tajā Sharepoint saitē, ko uztaisīji, man nebija Access Rights, lai tur pievienotu jaunu failu. https://rtucloud1-my.sharepoint.com/:w:/g/personal/edgars_zoltners_1_edu_rtu_lv/EbSLNG-xY_JIpkO6hc8kGSoBT7f97B8WcY_kRtnMBnTd2Q?e=EdpDKr

**Comment by edzya** [comment]
@svinacienitajs https://rtucloud1.sharepoint.com/sites/RTUScheduleservice/Shared%20Documents/Forms/AllItems.aspx

**Comment by edzya** [comment]
@svinacienitajs šito issue varam likt uz Done ?
