### ISSUE TITLE
Izveidot prezentāciju

### ISSUE THREAD

**Issue by edzya** [edzya/RTU_project#3]
Prezentācija par projektu
Success criteria:
Less text, more descriptive images;
At least 6 slides/pages

**Comment by svinacienitajs** [comment]
@edzya https://rtucloud1.sharepoint.com/:p:/r/sites/RTUScheduleservice/_layouts/15/Doc.aspx?sourcedoc=%7B96C16320-ABD9-44B0-A578-C31E203DBE74%7D&file=RTU%20SCHEDULE%20SERVICE.pptx&action=edit&mobileredirect=true - Es te plati uztaisiju , pagaidam pauzi uzmetīšu.
